bar/urls.py
from bar import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.defaults import page_not_found, server_error

app_name = "Bar"

urlpatterns = [
    path('', views.bar, name="bar"),
    path('expenses', views.bar_expenses, name="bar_expenses"),
    path('expenses/save', views.bar_expenses_save, name="bar_expenses_save"),
    path('pays/save', views.bar_pays_save, name="bar_pays_save"),
    path('delete/<int:pk>', views.bar_employee_delete, name="bar_employee_delete"),
    path('salary', views.bar_salary, name="bar_salary"),
    path('salary/save', views.bar_salary_save, name="bar_salary_save"),
    path('invent', views.bar_invent, name="bar_invent"),
    path('end', views.bar_end, name="bar_end"),
    path('invent', views.bar_invent, name="bar_invent"),
    path('invent/form/<str:storageId>', views.bar_invent_form, name="bar_invent_form"),
    path('invent/table', views.bar_invent_table, name="bar_invent_table"),
    path('end/save', views.bar_end_save, name="bar_end_save"),
    path('auto_salary', views.bar_auto_salary, name="bar_auto_salary"),
    path('main_salary', views.bar_salary3, name="bar_salary3"),
    path('main_salary/save', views.bar_salary3_save, name="bar_salary3_save"),
    path('expenses/delete/<int:id>', views.bar_expenses_delete, name="bar_expenses_delete"),
    path('employee', views.bar_employee_salary_now, name="bar_employee_salary_now"),
    path('employee/previous', views.bar_employee_salary_previous, name="bar_employee_salary_previous"),
    path('calendar', views.bar_calendar, name="bar_calendar"),
    path('calendar/insert', views.bar_calendar_insert, name="bar_calendar_insert"),
    path('blacklist', views.bar_blacklist, name="bar_blacklist"),
    path('invent/second', views.bar_invent_second, name="bar_invent_second"),
    path('invent/second/form/<str:storageId>', views.bar_invent_form_second, name="bar_invent_form_second"),
    path('invent/second/table', views.bar_invent_table_second, name="bar_invent_table_second"),
    path('request/beer', views.bar_beer_request, name="bar_beer_request"),
    path('request/box', views.bar_box_request, name="bar_box_request"),
    path('request/products', views.bar_products_request, name="bar_products_request"),
    path('request/bar', views.bar_drinks_request, name="bar_drinks_request"),
    path('arrival/beer', views.bar_beer_arrival, name="bar_beer_arrival"),
    path('arrival/beer/delete', views.bar_beer_arrival_delete, name="bar_beer_arrival_delete"),
    path('arrival/drinks', views.bar_drinks_arrival, name="bar_drinks_arrival"),
    path('arrival/drinks/delete', views.bar_drinks_arrival_delete, name="bar_drinks_arrival_delete"),
    path('request/beer/delete', views.bar_beer_request_delete, name="bar_beer_request_delete"),
    path('request/hoz', views.bar_hoz_request, name="bar_hoz_request"),
]

barv2/urls.py
from django.urls import path
from bar import views
app_name = "Bar"

urlpatterns = [
    path('', views.index, name="index"),
    path('timetable/save', views.timetable_save, name="timetable_save"),
    path('employee/delete', views.timetable_delete, name="timetable_delete"),
    path('expenses', views.expenses, name="expenses"),
    path('expenses/save', views.expenses_save, name="expenses_save"),
    path('expenses/delete', views.expenses_delete, name="expenses_delete"),
    path('pays/save', views.pays_save, name="pays_save"),
    path('salary', views.salary, name="salary"),
    path('salary/save', views.salary_save, name="salary_save"),
    path('month_salary', views.month_salary, name="month_salary"),
    path('month_salary/save', views.month_salary_save, name="month_salary_save"),
    path('auto_salary', views.auto_salary, name="auto_salary"),
    path('end', views.end_day, name="end"),
    path('end/save', views.end_day_save, name="end_save"),
    path('inventory', views.inventory, name="inventory"),
    path('inventory/table', views.inventory_table, name="inventory_table"),
    path('inventory/form/<str:storageId>', views.inventory_form, name="inventory_form")
]

lk/urls.py
from lk import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.defaults import page_not_found, server_error

app_name = "LK"

urlpatterns = [
    path('', views.lk, name="lk_lk"),
    path('money', views.money, name="lk_money"),
    path('timetable', views.timetable, name="lk_timetable"),
    path('salary', views.salary, name="lk_salary"),
    path('expenses', views.expenses, name="lk_expenses"),
    path('employee', views.employee, name="lk_employee"),
    path('employee/new', views.employee_new, name="lk_employee_new"),
    path('employee/edit', views.employee_edit, name="lk_employee_edit"),
    path('employee/save', views.employee_save, name="lk_employee_save"),
    path('<str:data>/delete', views.delete, name="lk_delete"),
    path('money/edit', views.money_edit, name="lk_money_edit"),
    path('salary/edit', views.salary_edit, name="lk_salary_edit"),
    path('salary/new', views.salary_new, name="lk_salary_new"),
    path('timetable/edit', views.timetable_edit, name="lk_timetable_edit"),
    path('timetable/new', views.timetable_new, name="lk_timetable_new"),
    path('expenses/new', views.expenses_new, name="lk_expenses_new"),
    path('expenses/edit', views.expenses_edit, name="lk_expenses_edit"),
    path('money/update', views.update_end_day, name="lk_update_end_day"),
    path('salary/calculation', views.salary_calculation, name="lk_salary_calculation"),
    path('salary/total_calculation', views.salary_total_calculation, name="lk_salary_total_calculation"),
    path('salary/employee_calculation', views.salary_employee_calculation, name="lk_salary_employee_calculation"),
    path('salary/update', views.salary_calculation_update, name="lk_salary_calculation_update"),
    path('salary/employee/send', views.salary_employee_send, name="lk_salary_employee_send"),
    path('fine', views.fine, name="lk_fine"),
    path('fine/save', views.fine_save, name="lk_fine_save"),
    path('new/fine/save', views.new_fine_save, name="lk_new_fine_save"),
    path('mysql/prepare', views.mysql_prepare, name="lk_mysql_prepare"),
    path('pays', views.pays, name="lk_pays"),
    path('blacklist', views.blacklist, name="lk_blacklist"),
    path('employee/comeback', views.employee_comeback, name="lk_employee_comeback"),
    path('pays/edit', views.pays_edit, name="lk_pays_edit"),
    path('pays/new', views.pays_new, name="pays_new"),
    path('bars', views.bars, name="lk_bars"),
    path('statement', views.bank_parser, name="bank_parser"),
    path('statement/cards', views.statement_cards, name="statement_cards"),
    path('employee_with_salary', views.employee_with_salary, name="employee_with_salary"),
    path('arrivals', views.arrivals, name="arrivals"),
    path('supplier_debt', views.supplier_debt, name="supplier_debt"),
    path('arrivals/new', views.beer_arrival_new, name="arrivals_new"),
    path('tovar_requests', views.tovar_requests, name="tovar_requests"),
    path('partners', views.partners, name="partners"),
    path('partners/edit', views.partners_edit, name="partners_edit"),
    path('arrivals/edit', views.arrivals_edit, name="arrivals_edit"),
    path('statement/cards/edit', views.cards_edit, name="cards_edit"),
    path('statement/edit', views.statement_edit, name="statement_edit"),
    path('statement/cards/sum', views.statement_cards_sum, name="statement_cards_sum"),
    path('arrivals/delete', views.arrivals_delete, name="arrivals_delete"),
    path('arrivals/copy', views.arrivals_copy, name="arrivals_copy"),
    path('revise', views.revise, name="revise"),
    path('tovar_requests/edit', views.tovar_requests_edit, name="tovar_requests_edit"),
]

povarDashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bar/', include('bar.urls')),
    path("login/", account_views.login, name="account_login"),
]

barv2/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = True` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Paymenttypes(models.Model):
    payment_id = models.CharField(max_length=256)
    code = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    is_active = models.IntegerField()

    class Meta:
        managed = True
        db_table = 'PaymentTypes'


class AutoSalary(models.Model):
    fio = models.CharField(max_length=256)
    date_at = models.CharField(max_length=256)
    storage_id = models.IntegerField()
    oklad = models.IntegerField()
    percent = models.IntegerField()
    premium = models.IntegerField()
    fine = models.IntegerField()
    total = models.IntegerField()

    class Meta:
        
        managed = True
        db_table = 'auto_salary'


class Blacklist(models.Model):
    date_at = models.DateField()
    storage_id = models.IntegerField()

    class Meta:
        
        managed = True
        db_table = 'blacklist'


class Brand(models.Model):
    name = models.CharField(max_length=24)
    url_api = models.CharField(max_length=255, blank=True, null=True)
    key_api = models.CharField(max_length=36, blank=True, null=True)
    key_updated_at = models.DateTimeField(blank=True, null=True)
    login_api = models.CharField(max_length=24, blank=True, null=True)
    pass_api = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        
        managed = True
        db_table = 'brand'


class Categories(models.Model):
    category_id = models.CharField(max_length=256)
    name = models.CharField(max_length=256)
    is_remains = models.IntegerField()
    is_sales = models.IntegerField()
    is_income = models.IntegerField()

    class Meta:
        
        managed = True
        db_table = 'categories'


class Employee(models.Model):
    code = models.CharField(max_length=256, blank=True, null=True)
    photo = models.IntegerField(blank=True, null=True)
    fio = models.CharField(max_length=64)
    birth_date = models.CharField(max_length=256, blank=True, null=True)
    address = models.CharField(max_length=256, blank=True, null=True)
    type = models.CharField(max_length=24, blank=True, null=True)
    storage_id = models.IntegerField(blank=True, null=True)
    phone = models.CharField(max_length=11, blank=True, null=True)
    first_work_day = models.CharField(max_length=256, blank=True, null=True)
    oklad = models.IntegerField()
    is_deleted = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        
        managed = True
        db_table = 'employee'


class Expenses(models.Model):
    created_at = models.DateField()
    date_at = models.DateField()
    storage_id = models.IntegerField()
    name = models.CharField(max_length=128)
    sum = models.IntegerField()
    comment = models.CharField(max_length=256, blank=True, null=True)
    is_bn = models.IntegerField()

    class Meta:
        
        managed = True
        db_table = 'expenses'


class ExpensesSource(models.Model):
    text = models.CharField(max_length=256, blank=True, null=True)
    type = models.IntegerField()
    is_active = models.IntegerField()
    input_name = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        
        managed = True
        db_table = 'expenses_source'


class Inventory(models.Model):
    name = models.CharField(max_length=256)
    amount = models.CharField(max_length=256)
    difference = models.CharField(max_length=256)
    fact = models.CharField(max_length=256)
    garazh = models.IntegerField(blank=True, null=True)
    esenina = models.IntegerField(blank=True, null=True)
    nevkipelogo = models.IntegerField(blank=True, null=True)
    cherkasskaya = models.IntegerField(blank=True, null=True)
    chekistov = models.IntegerField(blank=True, null=True)
    sormovskaya = models.IntegerField(blank=True, null=True)
    itogo = models.IntegerField(blank=True, null=True)

    class Meta:
        
        managed = True
        db_table = 'inventory'


class Money(models.Model):
    created_at = models.DateField()
    date_at = models.DateField()
    storage_id = models.IntegerField()
    sum_cash_morning = models.IntegerField()
    sum_cash_end_day = models.IntegerField(blank=True, null=True)
    total_cash = models.IntegerField(blank=True, null=True)
    total_bn = models.IntegerField(blank=True, null=True)
    total_market = models.IntegerField(blank=True, null=True)
    total_day = models.IntegerField(blank=True, null=True)
    calculated = models.IntegerField(blank=True, null=True)
    difference = models.IntegerField(blank=True, null=True)
    total_salary = models.IntegerField(blank=True, null=True)
    total_expenses = models.IntegerField(blank=True, null=True)
    payin = models.IntegerField(blank=True, null=True)
    payout = models.IntegerField(blank=True, null=True)

    class Meta:
        
        managed = True
        db_table = 'money'


class PayinText(models.Model):
    text = models.CharField(max_length=256)

    class Meta:
        
        managed = True
        db_table = 'payin_text'


class Pays(models.Model):
    created_at = models.DateField()
    date_at = models.DateField()
    storage_id = models.IntegerField()
    type = models.IntegerField()
    sum = models.IntegerField()
    comment = models.CharField(max_length=128)

    class Meta:
        
        managed = True
        db_table = 'pays'


class Positions(models.Model):
    position = models.CharField(max_length=256, blank=True, null=True)
    type = models.CharField(max_length=64)
    oklad = models.IntegerField(blank=True, null=True)

    class Meta:
        
        managed = True
        db_table = 'positions'


class Products(models.Model):
    product_id = models.CharField(max_length=256, blank=True, null=True)
    parent_id = models.CharField(max_length=256, blank=True, null=True)
    num = models.CharField(max_length=256, blank=True, null=True)
    code = models.CharField(max_length=256, blank=True, null=True)
    name = models.CharField(max_length=256, blank=True, null=True)
    product_type = models.CharField(max_length=256, blank=True, null=True)
    main_unit = models.CharField(max_length=256, blank=True, null=True)
    product_category = models.CharField(max_length=256, blank=True, null=True)
    supplier_id = models.CharField(max_length=256)
    minimal = models.IntegerField(blank=True, null=True)
    wanna_order = models.IntegerField(blank=True, null=True)

    class Meta:
        
        managed = True
        db_table = 'products'


class Salary(models.Model):
    created_at = models.DateField()
    date_at = models.DateField()
    storage_id = models.IntegerField()
    employee_id = models.IntegerField()
    type = models.IntegerField()
    oklad = models.IntegerField()
    percent = models.IntegerField()
    premium = models.IntegerField()
    month = models.CharField(max_length=64, blank=True, null=True)
    days = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        
        managed = True
        db_table = 'salary'


class Storages(models.Model):
    code = models.CharField(max_length=256)
    storage_id = models.CharField(max_length=256)
    pointofsale = models.CharField(max_length=256, blank=True, null=True)
    name = models.CharField(max_length=256)
    yur_lico = models.CharField(max_length=128)

    class Meta:
        
        managed = True
        db_table = 'storages'


class Timetable(models.Model):
    created_at = models.DateField()
    date_at = models.DateField()
    storage_id = models.IntegerField()
    employee_id = models.IntegerField()
    position_id = models.IntegerField()
    oklad = models.IntegerField()

    class Meta:
        
        managed = True
        db_table = 'timetable'

templates/barv2/end.html
{% extends 'bar/base.html' %}

{% block body %}
<div class="card mb-4">
    <div class="card-header">
        <b>Конец дня (№: {{ sessionId }})</b>
    </div>
    <div class="card-body">
        {% if openDate is not None %}
        Открыта: {{ openDate }} <br>
        {% endif %}
        {% if closeDate is not None %}
        Закрыта: {{ closeDate }} <br>
        {% endif %}
        <div class="dropdown-divider"></div>
        Выручка: {{ payOrders }} <br>
        {% if sumNal > 0 %}
        Наличные: {{ sumNal }} ({{ nal }} + {{ nal_point }}) <br>
        {% endif %}
        {% if sumBN > 0 %}
        Банковская карта(авт.ч): {{ sumBN }} <br>
        {% endif %}
        {% if yandex > 0 %}
        Яндекс ЕДА: {{ yandex }} <br>
        {% endif %}
        {% if delivery > 0 %}
        Деливери: {{ delivery }} <br>
        {% endif %}
        {% if sum_for_percent > 0 %}
        Сумма для начисления процентов: {{ sum_for_percent }} <br>
        {% endif %}
        <div class="dropdown-divider"></div>
        Касса утро: {{ morning }} <br>
        {% if sumNal > 0 %}
        Наличные: {{ sumNal }} ({{ nal }} + {{ nal_point }}) <br>
        {% endif %}
        {% if expensesNal > 0 %}
        Расходы нал: {{ expensesNal }} <br>
        {% endif %}
        {% if monthly_salary > 0 %}
        ЗП расчет: {{ monthly_salary }} <br>
        {% endif %}
        {% if total_salary > 0 %}
        ЗП Аванс: {{ total_salary }} <br>
        {% endif %}
        {% if payin > 0 %}
        Внесения: {{ payin }} <br>
        {% endif %}
        {% if payout > 0 %}
        Изъятия: {{ payout }} <br>
        {% endif %}
        <form action="{% url 'Bar:end_save' %}" method="post">
            {% csrf_token %}
            {% if end is None or end == '' %}
                {% if closeDate is not None %}
                <br>
                <input type="hidden" name="sumNal" value="{{ sumNal }}">
                <input type="hidden" name="code" value="{{ code }}">
                <input type="hidden" name="sumBN" value="{{ sumBN }}">
                <input type="hidden" name="total_day" value="{{ payOrders }}">
                <input type="hidden" name="yandex" value="{{ yandex }}">
                <input type="hidden" name="delivery" value="{{ delivery }}">
                <label for="cash">Остаток наличных в кассе</label>
                <input type="tel" id="cash" name="cash" class="form-control" placeholder="Пересчитайте остатки в кассе"> <br>
                <button type="submit" class="btn btn-success">Сохранить</button>
                {% endif %}
            {% else %}
            <div class="dropdown-divider"></div>
            Остаток в кассе: {{ end }} <br> Расхождение: {{ difference }}
            Расчетный: {{ calculated }}
            {% endif %}
        </form>
    </div>
</div>
{% endblock %}

templates/barv2/expenses.html
{% extends 'bar/base.html' %}

{% block body %}
    <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header">
            <b>Расходы {% if expenses_sum is None %}0{% else %}{{ expenses_sum }}{% endif %} ({% if all_expenses_nal is None %}0{% else %}{{ all_expenses_nal }}{% endif %}+{% if all_expenses_card is None %}0{% else %}{{ all_expenses_card }}{% endif %})</b>
        </div>
        <div class="card-body">
            <table class="table table-sm">
                <thead>
                    <th>Расход</th>
                    <th>Комментарий</th>
                    <th>Сумма</th>
                    <th></th>
                </thead>
                <tbody>
                    {% for expense in expenses %}
                        <tr>
                            <td>{{ expense.name }} ({% if expense.is_bn == 0 %}Из кассы{% else %}Картой{% endif %})</td>
                            <td>{{ expense.comment }}</td>
                            <td>{{ expense.sum }}</td>
                            <td>
                                <a data-bs-toggle="modal" data-bs-target="#exampleModal{{ expense.id }}">
                                    <i data-feather="x-circle"></i>
                                </a>
                            </td>
                            <div class="modal fade" id="exampleModal{{ expense.id }}" tabindex="-1" aria-labelledby="exampleModalLabel{{ expense.id }}" aria-hidden="true">
                                <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel{{ expense.id }}">Вы действительно хотите удалить расход?</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Закрыть"></button>
                                    </div>
                                    <div class="modal-body">
                                        <p>{{ expense.name }} ({% if expense.is_bn == 0 %}Из кассы{% else %}Картой{% endif %}) - {{ expense.sum }}</p>
                                    </div>
                                    <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Закрыть</button>
                                    <a href="/bar/expenses/delete?code={{ code }}&id={{ expense.id }}" class="btn btn-danger">Удалить</a>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <br>
            <form action="{% url 'Bar:expenses_save' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="code" id="code" value="{{ code }}">
                <select name="pay_type" id="pay_type" class="form-select" required>
                    <option value="" selected="">Тип оплаты</option>
                    <option value="0">Из кассы</option>
                    <option value="1">Картой</option>
                </select>
                <br>
                <table>
                    {% for row in rows %}
                        {% if row.text == 'Такси' %}
                            <tr>
                                <td>Такси</td>
                                <td>
                                    <select name="taxi_comment" id="taxi_comment" class="form-select">
                                        <option value="" selected id="option" name="option">Выберите..</option>
                                        {% for t in timetable %}
                                            {% for employee in employees %}
                                                {% if t.employee_id == employee.id %}
                                                    <option value="{{ employee.fio }}">{{ employee.fio }}</option>
                                                {% endif %}
                                            {% endfor %}
                                        {% endfor %}
                                    </select>
                                </td>
                                <td><input type="tel" name="taxi_sum" id="taxi_sum" value="" placeholder="Сумма" class="form-control" onkeyup="getValue()"></td>
                            </tr>
                        {% else %}
                            <tr>
                                <td>{{ row.text }}</td>
                                <td><input type="text" name="{{ row.input_name }}_comment" id="{{ row.input_name }}_comment" value="" placeholder="Комментарий" class="form-control"></td>
                                <td><input type="tel" name="{{ row.input_name }}_sum" id="{{ row.input_name }}_sum" value="" placeholder="Сумма" class="form-control"></td>
                            </tr>
                        {% endif %}
                    {% endfor %}
                </table>
                <br>
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
    </div>
    <div class="card shadow-lg border-0 rounded-lg mt-5">
        <div class="card-header">
            <b>Внесение/Изъятие ({% if all_pays is None %}0{% else %}{{ all_pays }}{% endif %})</b>
        </div>
        <div class="card-body">
            <table class="table table-hover my-0 table-sm">
                <thead>
                    <th>Вид</th>
                    <th>Комментарий</th>
                    <th>Сумма</th>
                </thead>
                <tbody>
                    {% for pay in pays %}
                        <tr>
                            <td>
                                {% if pay.type == 2 %}
                                    Изъятие
                                {% else %}
                                    Внесение
                                {% endif %}
                            </td>
                            <td>{{ pay.comment }}</td>
                            <td>{{ pay.sum }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <br>
            <form action="{% url 'Bar:pays_save' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="code" id="code" value="{{ code }}">
                <table>
                    <tr>
                        <td>Внесение:</td>
                        <td>
                            <select name="payin_comment" id="payin_comment" class="form-select">
                                <option value="" selected="">Выберите..</option>
                                {% for d in data %}
                                    <option value="{{ d.text }}">{{ d.text }}</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td><input value="" type="tel" name="payin_sum" id="payin_sum" placeholder="Сумма" class="form-control"></td>
                    </tr>
                    <tr>
                        <td>Изъятие:</td>
                        <td>
                            <select name="payout_comment" id="payout_comment" class="form-select">
                                <option value="" selected="">Выберите..</option>
                                {% for d in data %}
                                    {% if d.text != 'Масло' %}
                                        <option value="{{ d.text }}">{{ d.text }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                        </td>
                        <td><input value="" type="tel" name="payout_sum" id="payout_sum" placeholder="Сумма" class="form-control"></td>
                    </tr>
                </table>
                <br>
                <button type="submit" class="btn btn-success">Сохранить</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/barv2/inventory.html
{% extends 'bar/base.html' %}

{% block body %}
<div class="card mb-4">
    <div class="card-header">
        <p><b>Инвентаризация</b></p><br>
        Основной бармен: {{ barmen }}
    </div>
    <div class="card-body">
        <form action="{% url 'Bar:inventory_form' storageId %}" method="post">
            {% csrf_token %}
            <table>
                {% for product in bar_products %}
                    <tr>
                        <td>{{ product.name }}</td>
                        <td><input type="tel" name="{{ product.num }}" id="{{ product.num }}" class="form-control" value="0" size="2"></td>
                    </tr>
                {% endfor %}
            </table>
            <input type="hidden" name="page_code" value="{{ code }}">
            <input type="hidden" name="barmen" value="{{ barmen }}">
            <button type="submit" class="btn btn-success">Отправить</button>
        </form>
    </div>
</div>
{% endblock %}

templates/barv2/salary.html
{% extends 'bar/base.html' %}

{% block body %}
<div class="card shadow-lg border-0 rounded-lg mt-5">
    <div class="card-header">
        <b>Зарплата (выплачено: {% if salary_sum is None %}0{% else %}{{ salary_sum }}{% endif %})</b>
    </div>
    <div class="card-body">
        <table class="table table-sm">
            <thead>
                <th>ФИО</th>
                <th>Оклад</th>
                <th>Процент</th>
                <th>Премия</th>
                <th>Итого</th>
            </thead>
            <tbody>
                {% for salary in salaries %}
                    <tr>
                        <td>
                            {% for employee in employees %}
                                {% if salary.employee_id == employee.id %}
                                    {{ employee.fio }}
                                {% endif %}
                            {% endfor %}
                        </td>
                        <td>{{ salary.oklad }}</td>
                        <td>{{ salary.percent }}</td>
                        <td>{{ salary.premium }}</td>
                        <td></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        <form action="{% url 'Bar:salary_save' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="code" id="code" value="{{ code }}">
            <table>
                {% for t in timetable %}
                    <tr>
                        <td>{% for employee in employees %}{% if employee.id == t.employee_id %}{{ employee.fio }}{% endif %}{% endfor %}: </td>
                        <td><input type="tel" class="form-control" id="[{{t.employee_id}}][oklad]" name="[{{t.employee_id}}][oklad]" placeholder="Оклад"></td>
                        <td><input type="tel" class="form-control" id="[{{t.employee_id}}][percent]" name="[{{t.employee_id}}][percent]" placeholder="Процент"></td>
                        {% if 'вызывной' in t.position %}
                        <td><input type="tel" class="form-control" id="[{{t.employee_id}}][premium]" name="[{{t.employee_id}}][premium]" placeholder="Премия"></td>
                        {% else %}
                        <td><input type="hidden" class="form-control" id="[{{t.employee_id}}][premium]" name="[{{t.employee_id}}][premium]" placeholder="Премия"></td>
                        {% endif %}
                        <input type="hidden" name="employee_id[{{ t.employee_id }}]" id="employee_id[{{ t.employee_id }}]" value="{{ t.employee_id }}">
                    </tr>
                {% endfor %}
            </table>
            <br>
            <button type="submit" class="btn btn-success">Сохранить</button>
        </form>
    </div>
</div>
{% endblock %}