iiko/urls.py
from iiko import views
from django.urls import path


app_name = "IIKO"

urlpatterns = [
    path('', views.iiko, name="iiko"),
    path('suppliers', views.suppliers, name="suppliers"),
    path('suppliers/edit', views.supplier_edit, name="supplier_edit"),
    path('nomenclature', views.nomenclature, name="nomenclature"),
    path('categories', views.categories, name="categories"),
    path('sales_by_types', views.sales_by_types, name="sales_by_types"),
    path('sales', views.sales, name="sales"),
    path('arrivals', views.arrivals, name="arrivals"),
    path('inventory', views.inventory, name="inventory"),
    path('nomenclature/edit', views.nomenclature_edit, name="nomenclature_edit"),
    path('inventory/send', views.inventory_send, name="inventory_send")
]

lk/urls.py
from lk import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.defaults import page_not_found, server_error

app_name = "LK"

urlpatterns = [
    path('', views.lk, name="lk_lk"),
    path('money', views.money, name="lk_money"),
    path('timetable', views.timetable, name="lk_timetable"),
    path('salary', views.salary, name="lk_salary"),
    path('expenses', views.expenses, name="lk_expenses"),
    path('employee', views.employee, name="lk_employee"),
    path('employee/new', views.employee_new, name="lk_employee_new"),
    path('employee/edit', views.employee_edit, name="lk_employee_edit"),
    path('employee/save', views.employee_save, name="lk_employee_save"),
    path('<str:data>/delete', views.delete, name="lk_delete"),
    path('money/edit', views.money_edit, name="lk_money_edit"),
    path('salary/edit', views.salary_edit, name="lk_salary_edit"),
    path('salary/new', views.salary_new, name="lk_salary_new"),
    path('timetable/edit', views.timetable_edit, name="lk_timetable_edit"),
    path('timetable/new', views.timetable_new, name="lk_timetable_new"),
    path('expenses/new', views.expenses_new, name="lk_expenses_new"),
    path('expenses/edit', views.expenses_edit, name="lk_expenses_edit"),
    path('money/update', views.update_end_day, name="lk_update_end_day"),
    path('salary/calculation', views.salary_calculation, name="lk_salary_calculation"),
    path('salary/total_calculation', views.salary_total_calculation, name="lk_salary_total_calculation"),
    path('salary/employee_calculation', views.salary_employee_calculation, name="lk_salary_employee_calculation"),
    path('salary/update', views.salary_calculation_update, name="lk_salary_calculation_update"),
    path('salary/employee/send', views.salary_employee_send, name="lk_salary_employee_send"),
    path('fine', views.fine, name="lk_fine"),
    path('fine/save', views.fine_save, name="lk_fine_save"),
    path('new/fine/save', views.new_fine_save, name="lk_new_fine_save"),
    path('mysql/prepare', views.mysql_prepare, name="lk_mysql_prepare"),
    path('pays', views.pays, name="lk_pays"),
    path('blacklist', views.blacklist, name="lk_blacklist"),
    path('employee/comeback', views.employee_comeback, name="lk_employee_comeback"),
    path('pays/edit', views.pays_edit, name="lk_pays_edit"),
    path('pays/new', views.pays_new, name="pays_new"),
    path('bars', views.bars, name="lk_bars"),
    path('statement', views.bank_parser, name="bank_parser"),
    path('statement/cards', views.statement_cards, name="statement_cards"),
    path('employee_with_salary', views.employee_with_salary, name="employee_with_salary"),
    path('arrivals', views.arrivals, name="arrivals"),
    path('supplier_debt', views.supplier_debt, name="supplier_debt"),
    path('arrivals/new', views.beer_arrival_new, name="arrivals_new"),
    path('tovar_requests', views.tovar_requests, name="tovar_requests"),
    path('partners', views.partners, name="partners"),
    path('partners/edit', views.partners_edit, name="partners_edit"),
    path('arrivals/edit', views.arrivals_edit, name="arrivals_edit"),
    path('statement/cards/edit', views.cards_edit, name="cards_edit"),
    path('statement/edit', views.statement_edit, name="statement_edit"),
    path('statement/cards/sum', views.statement_cards_sum, name="statement_cards_sum"),
    path('arrivals/delete', views.arrivals_delete, name="arrivals_delete"),
    path('arrivals/copy', views.arrivals_copy, name="arrivals_copy"),
    path('revise', views.revise, name="revise"),
    path('tovar_requests/edit', views.tovar_requests_edit, name="tovar_requests_edit"),
]

povarDashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bar/', include('bar.urls')),
    path("login/", account_views.login, name="account_login"),
]

iiko/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Suppliers, Categories, Products, Storages, IikoArrivals, BeerArrival
import xml.etree.ElementTree as ET
import json
from functions import *


@login_required
def iiko(request):
    return render(request, 'base.html')


@login_required
def suppliers(request):
    root = ET.fromstring(getIikoSuppliersByBrand())

    for country in root.findall('employee'):
        id = country.find('id').text
        code = country.find('code').text
        name = country.find('name').text
        deleted = country.find('deleted').text
        supplier = country.find('supplier').text
        employee = country.find('employee').text
        client = country.find('client').text

        obj = Suppliers.objects.filter(supplier_id=id).count()
        if obj == 0:
            supplier = Suppliers(
                supplier_id=id,
                code=code,
                name=name,
                deleted=deleted,
                supplier=supplier,
                employee=employee,
                client=client,
                friendly_name=name
            )
            supplier.save()
    return render(request, 'iiko/suppliers.html', context={
        "suppliers": Suppliers.objects.all(),
    })


@login_required
def supplier_edit(request):
    if request.method == 'POST':
        category = request.POST["category"]
        name = request.POST["name"]

        record = Suppliers.objects.get(id=request.GET.get('id'))
        record.friendly_name = name
        record.category = category
        record.is_revise = request.POST.get("is_revise") if request.POST.get('is_revise') is not None else 0
        record.save()

        return redirect('/iiko/suppliers')

    return render(request, 'iiko/supplier_edit.html', context={
        "categories": Categories.objects.all(),
        "supplier": Suppliers.objects.get(id=request.GET.get('id'))
    })


@login_required()
def nomenclature(request):
    if request.GET.get('update') is not None:
        root = ET.fromstring(getIikoNomenclatureByBrand())

        id = ''
        parentId = ''
        num = ''
        code = ''
        name = ''
        productType = ''
        productCategory = ''
        mainUnit = ''

        for country in root.findall('productDto'):
            if country.find('id') is not None:
                id = country.find('id').text
            if country.find('parentId') is not None:
                parentId = country.find('parentId').text
            if country.find('num') is not None:
                num = country.find('num').text
            if country.find('code') is not None:
                code = country.find('code').text
            if country.find('name') is not None:
                name = country.find('name').text
            if country.find('productType') is not None:
                productType = country.find('productType').text
            if country.find('mainUnit') is not None:
                mainUnit = country.find('mainUnit').text
            if country.find('productCategory') is not None:
                productCategory = country.find('productCategory').text

            if country.find('productGroupType') is None:
                if country.find('productType').text != 'MODIFIER':
                    if country.find('productCategory') is not None:
                        obj = Products.objects.filter(product_id=id).count()
                        if obj == 0:
                            product = Products(
                                product_id=id,
                                parent_id=parentId,
                                num=num,
                                code=code,
                                name=name,
                                product_type=productType,
                                main_unit=mainUnit,
                                product_category=productCategory,
                            )
                            product.save()
                        else:
                            product = Products.objects.get(product_id=id)
                            product.name = name
                            product.product_type = productType
                            product.main_unit = mainUnit
                            product.product_category = productCategory
                            product.save()
                    else:
                        obj = Products.objects.filter(product_id=id).count()
                        if obj == 0:
                            product = Products(
                                product_id=id,
                                parent_id=parentId,
                                num=num,
                                code=code,
                                name=name,
                                product_type=productType,
                                main_unit=mainUnit,
                                product_category='None',
                            )
                            product.save()
                        else:
                            object = Products.objects.get(product_id=id)
                            object.name = name
                            object.product_type = productType
                            object.main_unit = mainUnit
                            object.product_category = 'None'
                            object.save()
        return redirect('/iiko/nomenclature')
    return render(request, 'iiko/nomenclature.html', context={
        "type": request.GET.get('type'),
        "products": Products.objects.all(),
        "suppliers": Suppliers.objects.all()
    })


@login_required()
def nomenclature_edit(request):
    if request.method == 'POST':
        supplier = request.POST["supplier"]
        wanna_order = request.POST["wanna_order"]
        minimal = request.POST["minimal"]

        obj = Products.objects.get(id=request.GET.get('id'))
        obj.supplier_id = supplier
        obj.wanna_order = wanna_order
        obj.minimal = minimal
        obj.save()

        rows = BeerArrival.objects.filter(product=request.GET.get('id'))
        for row in rows:
            row.supplier = supplier
            row.save()

        return redirect('/iiko/nomenclature')
    return render(request, 'iiko/nomenclature_edit.html', context={
        "suppliers": Suppliers.objects.all(),
        "object": Products.objects.get(id=request.GET.get('id'))
    })


@login_required()
def categories(request):
    if request.GET.get('update') is not None:
        jsonData = getIikoUserCategories()
        dictData = json.loads(jsonData)

        for i in range(len(dictData)):
            obj = Categories.objects.filter(category_id=dictData[i]["id"]).count()
            if obj == 0:
                category = Categories(
                    category_id=dictData[i]["id"],
                    name=dictData[i]["name"],
                    is_remains=0,
                    is_sales=0,
                    is_income=0
                )
                category.save()

        return redirect('/iiko/categories')
    return render(request, 'iiko/categories.html', context={
        "categories": Categories.objects.all()
    })


@login_required()
def sales(request):
    pass


@login_required()
def sales_by_types(request):
    pass


@login_required()
def arrivals(request):
    if request.method == 'POST':
        dateFrom = request.POST["dateFrom"]
        dateTo = request.POST["dateTo"]
        root = ET.fromstring(getIikoTovarNomenclature(dateFrom, dateTo))
        for c in root.findall('document'):
            document_id = c.find('id').text
            if IikoArrivals.objects.filter(document_id=document_id).count() == 0:
                date = c.find('incomingDate').text
                store = c.find('defaultStore').text
                supplier = c.find('supplier').text
                number = '' if c.find('incomingDocumentNumber') is None else c.find('incomingDocumentNumber').text
                comment = '' if c.find('comment') is None else c.find('comment').text
                storage_id = Storages.objects.get(storage_id=store).id
                supplier_id = Suppliers.objects.get(supplier_id=supplier).id
                for cc in c.findall('items/item'):
                    tovar = cc.find('product').text
                    sum = cc.find('sum').text
                    amount = cc.find('amount').text
                    comment = '' if comment is None else comment
                    paid_sum = 0 if 'не' in comment or len(comment) == 0 else sum
                    try:
                        product_category = Products.objects.get(product_id=tovar).product_category
                    except Products.DoesNotExist:
                        product_category = -1
                    try:
                        category_id = Categories.objects.get(name=product_category).id
                    except Categories.DoesNotExist:
                        category_id = -1
                    try:
                        product_id = Products.objects.get(product_id=tovar).id
                    except Products.DoesNotExist:
                        product_id = -1
                    row = IikoArrivals(
                        document_id=document_id,
                        date_at=date,
                        storage_id=storage_id,
                        supplier_id=supplier_id,
                        invoice_num=number,
                        product_id=product_id,
                        amount=-1 if amount is None else amount.split('.')[0],
                        sum=-1 if sum is None else sum.split('.')[0],

templates/iiko/categories.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <a href="/iiko/categories?update=1" class="btn btn-outline-primary">Обновить категории</a>
            <br>
            <table id="table_id" class="table table-striped table-bordered table-sm dt-responsive nowrap w-100">
                <thead>
                    <tr>
                        <th>Название</th>
                        <th>Участвует в остатках</th>
                        <th>Участвует в продажах</th>
                        <th>Участвует в поступлениях</th>
                        <th>Действия</th>
                    </tr>
                </thead>
                <tbody>
                    {% for category in categories %}
                    <tr>
                        <td>{{ category.name }}</td>
                        <td>{% if category.is_remains == 1 %}Да{% else %}Нет{% endif %}</td>
                        <td>{% if category.is_sales == 1 %}Да{% else %}Нет{% endif %}</td>
                        <td>{% if category.is_income == 1 %}Да{% else %}Нет{% endif %}</td>
                        <td><a href="/povar/iiko/categories/edit/{{ category.id }}"><i data-feather="edit"></i></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/iiko/inventory.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <form action="{% url 'IIKO:inventory' %}">
                <label for="storage_id">Заведение</label>
                <select class="form-select" id="storage_id" name="storage_id">
                    <option value="0" selected>Все</option>
                    {% for storage in storages %}
                        <option value="{{ storage.id }}">{{ storage.name }}</option>
                    {% endfor %}
                </select>
                <br>
                <label for="category">Категория</label>
                <select class="form-select" id="category" name="category">
                    {% for category in categories %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
                <br>
                <button type="submit" class="btn btn-success">Применить фильтр</button>
            </form>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-body">
            {% if storage_id == 0 %}
                <b>Все</b>
                <div class="table-responsive">
                    <table id="table_id" class="table table-sm table-hover">
                        <thead>
                            <tr>
                                <th>Заведение</th>
                                {% for product in products %}
                                    <th>{{ product.name }}</th>
                                {% endfor %}
                                <th>Итого</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for row in rows %}
                                {% for key, value in row.items %}
                                    <tr>
                                        <td>
                                            {% for storage in storages %}
                                                {% if key == storage.id %}
                                                    {{ storage.small_name }}
                                                {% endif %}
                                            {% endfor %}
                                        </td>
                                        {% for key, value in value.items %}
                                            <td>{{ value|floatformat }}</td>
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                {% for product in products %}
                                    <th></th>
                                {% endfor %}
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            {% else %}
                <b>
                    {% for storage in storages %}
                        {% if storage_id == storage.id %}
                            {{ storage.name }}
                        {% endif %}
                    {% endfor %}
                </b>
                <div class="table-responsive">
                    <table class="table table-sm table-hover">
                        <thead>
                            <tr>
                                <th>Продукт</th>
                                <th>Остаток</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for key, value in records.items %}
                                <tr>
                                    <td>{{ key }}</td>
                                    <td>{{ value|floatformat }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    $(() => {
        // Run datatable
        var table = $('#table_id').DataTable({
            language: {
                "url": "//cdn.datatables.net/plug-ins/1.11.1/i18n/ru.json"
            },
            lengthMenu: [10, 25, 50, 100, 200, 500],
            pageLength: 25,
            //responsive: true,

            drawCallback: function () {
                $('.dataTables_paginate > .pagination').addClass('pagination-sm') // make pagination small
            },
            footerCallback: function (row, data, start, end, display) {
                var api = this.api();
                // Remove the formatting to get integer data for summation
                var intVal = function (i) {
                    return typeof i === 'string' ?
                        i.replace(/[\$,]/g, '') * 1 :
                        typeof i === 'number' ?
                            i : 0;
                };
                let i = 0;
                while(i < {{ products.count }}) {
                    pageTotal4 = api.column(i+1, { page: 'current' }).data().reduce(function (a, b) {
                        return intVal(a) + intVal(b);
                    }, 0);
                    // Update footer
                    $(api.column(i+1).footer()).html(
                        '' + pageTotal4  //+ ' (' + total4 + ' total)'
                    );
                    i++;
                }
            }

        })
        // Apply column filter
        $('#table_id .dt-column-filter th').each(function (i) {
            $('input', this).on('keyup change', function () {
                if (table.column(i).search() !== this.value) {
                    table
                        .column(i)
                        .search(this.value)
                        .draw()
                }
            })
        })
        // Toggle Column filter function
        var responsiveFilter = function (table, index, val) {
            var th = $(table).find('.dt-column-filter th').eq(index)
            val === true ? th.removeClass('d-none') : th.addClass('d-none')
        }
        // Run Toggle Column filter at first
        $.each(table.columns().responsiveHidden(), function (index, val) {
            responsiveFilter('#table_id', index, val)
        })
        // Run Toggle Column filter on responsive-resize event
        table.on('responsive-resize', function (e, datatable, columns) {
            $.each(columns, function (index, val) {
                responsiveFilter('#table_id', index, val)
            })
        })
    })
</script>
{% endblock %}

templates/iiko/nomenclature_edit.html
{% extends 'lk/form_base.html' %}

{% block content %}
    <div class="card-body">
        <form action="{% url 'IIKO:nomenclature_edit' %}?id={{ object.id }}"
            method="post">
            {% csrf_token %}

            <div class="form-group">
                <label for="supplier">Поставщик</label>
                <select name="supplier" id="supplier"
                class="form-select">
                <option value="-1" selected>Выберите поставщика</option>
                {% for supplier in suppliers %}
                {% if object.supplier_id == supplier.supplier_id %}
                <option value="{{ supplier.supplier_id }}" selected>{{ supplier.name }}</option>
                {% else %}
                <option value="{{ supplier.supplier_id }}">{{ supplier.name }}</option>
                {% endif %}
                {% endfor %}
            </select>
            </div>
            <div class="form-group">
                <label for="minimal">Минимальное количество</label>
                <input type="text" id="minimal" name="minimal" class="form-control" placeholder="Введите минимальное количество" value="{{ object.minimal }}">
            </div>
            <div class="form-group">
                <label for="wanna_order">Заказать</label>
                <input type="text" id="wanna_order" name="wanna_order" class="form-control" placeholder="Введите количество для заказа" value="{{ object.wanna_order }}">
            </div>

            <button type="submit" class="btn btn-primary">
                Сохранить
            </button>
        </form>
    </div>
{% endblock %}

templates/iiko/supplier_edit.html
{% extends 'lk/form_base.html' %}

{% block content %}
    <div class="card-body">
        <form action="{% url 'IIKO:supplier_edit' %}?id={{ supplier.id }}"
            method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">Отображаемое имя</label>
                <input type="text" name="name" id="name" class="form-control" placeholder="Введите отображаемое имя" value="{{ supplier.friendly_name }}">
            </div>
            <div class="form-group">
                <label for="category">Категория</label>
                <select name="category" id="category" class="form-select">
                    {% for category in categories %}
                        {% if category.name == supplier.category %}
                        <option value="{{ category.name }}" selected>{{ category.name }}</option>
                        {% else %}
                        <option value="{{ category.name }}">{{ category.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="is_revise">Участвует в сверке</label>
                <input type="checkbox" value="1" id="is_revise" name="is_revise" {% if supplier.is_revise == 1 %}checked{% endif %}>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">
                    Сохранить
                </button>
            </div>
        </form>
    </div>
{% endblock %}

templates/iiko/suppliers.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <div class="table-responsive">
                <table id="table_id" class="table table-striped table-bordered table-sm dt-responsive nowrap w-100">
                    <thead>
                        <tr class="column-filter dt-column-filter">
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                        </tr>
                        <tr>
                            <th>Наименование</th>
                            <th>Категория</th>
                            <th>Уч. в сверке</th>
                            <th>Действия</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for supplier in suppliers %}
                        <tr>
                            <td>{{ supplier.name }} ({{ supplier.friendly_name }})</td>
                            <td>{{ supplier.category }}</td>
                            <td>{% if supplier.is_revise == 1 %}+{% else %}-{% endif %}</td>
                            <td><a href="{% url 'IIKO:supplier_edit' %}?id={{ supplier.id }}"><i data-feather="edit"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    $(() => {
        // Run datatable
        var table = $('#table_id').DataTable({
            language: {
                "url": "//cdn.datatables.net/plug-ins/1.11.1/i18n/ru.json"
            },
            lengthMenu: [10, 25, 50, 100, 200, 500],
            pageLength: 25,
            responsive: true,
        })
        // Apply column filter
        $('#table_id .dt-column-filter th').each(function (i) {
            $('input', this).on('keyup change', function () {
                if (table.column(i).search() !== this.value) {
                    table
                        .column(i)
                        .search(this.value)
                        .draw()
                }
            })
        })
        // Toggle Column filter function
        var responsiveFilter = function (table, index, val) {
            var th = $(table).find('.dt-column-filter th').eq(index)
            val === true ? th.removeClass('d-none') : th.addClass('d-none')
        }
        // Run Toggle Column filter at first
        $.each(table.columns().responsiveHidden(), function (index, val) {
            responsiveFilter('#table_id', index, val)
        })
        // Run Toggle Column filter on responsive-resize event
        table.on('responsive-resize', function (e, datatable, columns) {
            $.each(columns, function (index, val) {
                responsiveFilter('#table_id', index, val)
            })
        })
    })
</script>
{% endblock %}