bar/urls.py
from bar import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.defaults import page_not_found, server_error

app_name = "Bar"

urlpatterns = [
    path('', views.bar, name="bar"),
    path('expenses', views.bar_expenses, name="bar_expenses"),
    path('expenses/save', views.bar_expenses_save, name="bar_expenses_save"),
    path('pays/save', views.bar_pays_save, name="bar_pays_save"),
    path('delete/<int:pk>', views.bar_employee_delete, name="bar_employee_delete"),
    path('salary', views.bar_salary, name="bar_salary"),
    path('salary/save', views.bar_salary_save, name="bar_salary_save"),
    path('invent', views.bar_invent, name="bar_invent"),
    path('end', views.bar_end, name="bar_end"),
    path('invent', views.bar_invent, name="bar_invent"),
    path('invent/form/<str:storageId>', views.bar_invent_form, name="bar_invent_form"),
    path('invent/table', views.bar_invent_table, name="bar_invent_table"),
    path('end/save', views.bar_end_save, name="bar_end_save"),
    path('auto_salary', views.bar_auto_salary, name="bar_auto_salary"),
    path('main_salary', views.bar_salary3, name="bar_salary3"),
    path('main_salary/save', views.bar_salary3_save, name="bar_salary3_save"),
    path('expenses/delete/<int:id>', views.bar_expenses_delete, name="bar_expenses_delete"),
    path('employee', views.bar_employee_salary_now, name="bar_employee_salary_now"),
    path('employee/previous', views.bar_employee_salary_previous, name="bar_employee_salary_previous"),
    path('calendar', views.bar_calendar, name="bar_calendar"),
    path('calendar/insert', views.bar_calendar_insert, name="bar_calendar_insert"),
    path('blacklist', views.bar_blacklist, name="bar_blacklist"),
    path('invent/second', views.bar_invent_second, name="bar_invent_second"),
    path('invent/second/form/<str:storageId>', views.bar_invent_form_second, name="bar_invent_form_second"),
    path('invent/second/table', views.bar_invent_table_second, name="bar_invent_table_second"),
    path('request/beer', views.bar_beer_request, name="bar_beer_request"),
    path('request/box', views.bar_box_request, name="bar_box_request"),
    path('request/products', views.bar_products_request, name="bar_products_request"),
    path('request/bar', views.bar_drinks_request, name="bar_drinks_request"),
    path('arrival/beer', views.bar_beer_arrival, name="bar_beer_arrival"),
    path('arrival/beer/delete', views.bar_beer_arrival_delete, name="bar_beer_arrival_delete"),
    path('arrival/drinks', views.bar_drinks_arrival, name="bar_drinks_arrival"),
    path('arrival/drinks/delete', views.bar_drinks_arrival_delete, name="bar_drinks_arrival_delete"),
    path('request/beer/delete', views.bar_beer_request_delete, name="bar_beer_request_delete"),
    path('request/hoz', views.bar_hoz_request, name="bar_hoz_request"),
]

lk/urls.py
from lk import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.views.defaults import page_not_found, server_error

app_name = "LK"

urlpatterns = [
    path('', views.lk, name="lk_lk"),
    path('money', views.money, name="lk_money"),
    path('timetable', views.timetable, name="lk_timetable"),
    path('salary', views.salary, name="lk_salary"),
    path('expenses', views.expenses, name="lk_expenses"),
    path('employee', views.employee, name="lk_employee"),
    path('employee/new', views.employee_new, name="lk_employee_new"),
    path('employee/edit', views.employee_edit, name="lk_employee_edit"),
    path('employee/save', views.employee_save, name="lk_employee_save"),
    path('<str:data>/delete', views.delete, name="lk_delete"),
    path('money/edit', views.money_edit, name="lk_money_edit"),
    path('salary/edit', views.salary_edit, name="lk_salary_edit"),
    path('salary/new', views.salary_new, name="lk_salary_new"),
    path('timetable/edit', views.timetable_edit, name="lk_timetable_edit"),
    path('timetable/new', views.timetable_new, name="lk_timetable_new"),
    path('expenses/new', views.expenses_new, name="lk_expenses_new"),
    path('expenses/edit', views.expenses_edit, name="lk_expenses_edit"),
    path('money/update', views.update_end_day, name="lk_update_end_day"),
    path('salary/calculation', views.salary_calculation, name="lk_salary_calculation"),
    path('salary/total_calculation', views.salary_total_calculation, name="lk_salary_total_calculation"),
    path('salary/employee_calculation', views.salary_employee_calculation, name="lk_salary_employee_calculation"),
    path('salary/update', views.salary_calculation_update, name="lk_salary_calculation_update"),
    path('salary/employee/send', views.salary_employee_send, name="lk_salary_employee_send"),
    path('fine', views.fine, name="lk_fine"),
    path('fine/save', views.fine_save, name="lk_fine_save"),
    path('new/fine/save', views.new_fine_save, name="lk_new_fine_save"),
    path('mysql/prepare', views.mysql_prepare, name="lk_mysql_prepare"),
    path('pays', views.pays, name="lk_pays"),
    path('blacklist', views.blacklist, name="lk_blacklist"),
    path('employee/comeback', views.employee_comeback, name="lk_employee_comeback"),
    path('pays/edit', views.pays_edit, name="lk_pays_edit"),
    path('pays/new', views.pays_new, name="pays_new"),
    path('bars', views.bars, name="lk_bars"),
    path('statement', views.bank_parser, name="bank_parser"),
    path('statement/cards', views.statement_cards, name="statement_cards"),
    path('employee_with_salary', views.employee_with_salary, name="employee_with_salary"),
    path('arrivals', views.arrivals, name="arrivals"),
    path('supplier_debt', views.supplier_debt, name="supplier_debt"),
    path('arrivals/new', views.beer_arrival_new, name="arrivals_new"),
    path('tovar_requests', views.tovar_requests, name="tovar_requests"),
    path('partners', views.partners, name="partners"),
    path('partners/edit', views.partners_edit, name="partners_edit"),
    path('arrivals/edit', views.arrivals_edit, name="arrivals_edit"),
    path('statement/cards/edit', views.cards_edit, name="cards_edit"),
    path('statement/edit', views.statement_edit, name="statement_edit"),
    path('statement/cards/sum', views.statement_cards_sum, name="statement_cards_sum"),
    path('arrivals/delete', views.arrivals_delete, name="arrivals_delete"),
    path('arrivals/copy', views.arrivals_copy, name="arrivals_copy"),
    path('revise', views.revise, name="revise"),
    path('tovar_requests/edit', views.tovar_requests_edit, name="tovar_requests_edit"),
]

povarDashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from allauth.account import views as account_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bar/', include('bar.urls')),
    path("login/", account_views.login, name="account_login"),
]

bar/views.py
from django.shortcuts import render, redirect
from bar.models import \
    ExpensesSource, PayinText, Categories, Products, Inventory, Storages, Paymenttypes, Employee, Timetable, Money, \
    Expenses, Pays, \
    Salary, AutoSalary, Calendar, Blacklist, TovarRequests, Suppliers, BeerArrival, Povarlogs
from django.db.models import Sum
import xml.etree.ElementTree as ET
import json
from calendar import monthrange
from functions import *
import requests


def send_webhk(chat_id, message, id):
    send_text = ''
    if id == 1:  # crm
        send_text = 'https://api.telegram.org/botBOT_API/sendMessage?chat_id=' + chat_id + '&text=' + message
    elif id == 2:  # ?
        send_text = 'https://api.telegram.org/botBOT_API/sendMessage?chat_id=' + chat_id + '&text=' + message
    elif id == 3:  # test
        send_text = 'https://api.telegram.org/botBOT_API/sendMessage?chat_id=' + chat_id + '&text=' + message
    response = requests.get(send_text)
    return response.json()


# [ Functions ]

def update_money(pk, storage_id):
    row = -1
    if pk == 1:
        salary = Salary.objects.filter(date=getTime(),
                                       storage_id=storage_id).aggregate(Sum('itogo'))['itogo__sum']
        row = Money.objects.get(date_at=getTime(),
                                storage_id=storage_id)
        row.total_salary = salary
    elif pk == 2:
        expenses = \
            Expenses.objects.filter(date_at=getTime(),
                                    storage_id=storage_id).aggregate(Sum('sum'))['sum__sum']
        row = Money.objects.get(date_at=getTime(),
                                storage_id=storage_id)
        row.total_expenses = expenses
    total_cash = 0 if row.total_cash is None else row.total_cash
    total_expenses = 0 if row.total_expenses is None else row.total_expenses
    total_salary = 0 if row.total_salary is None else row.total_salary
    payin = 0 if row.payin is None else row.payin
    payout = 0 if row.payout is None else row.payout
    end_day = 0 if row.sum_cash_end_day is None else row.sum_cash_end_day
    row.difference = row.sum_cash_morning + total_cash - total_expenses - total_salary + payin - payout
    row.save()
    row.difference2 = end_day - int(row.difference)
    row.save()


# [ Pages ]
def bar(request):
    if request.method == 'POST':
        storage_id = request.POST["cafe"]
        codee = request.POST["code"]
        cafe = request.POST["cafee"]
        if Timetable.objects.filter(date_at=getTime(),
                                    storage_id=storage_id, position='Бармен основной').count() == 0:
            barmen = request.POST["barmen"]
        else:
            barmen = 0
        barmen_plus = request.POST["barmen_plus"]
        barmen_call = request.POST["barmen_call"]
        barmen_stazh = request.POST["barmen_stazh"]

        povar = request.POST["povar"]
        povar_plus = request.POST["povar_plus"]
        povar_call = request.POST["povar_call"]
        povar_stazh = request.POST["povar_stazh"]

        call = request.POST["call"]
        call2 = request.POST["call2"]

        sum_cash_morning = 0
        sum_cash_end_day = 0

        dateFromm = get_current_time() - datetime.timedelta(days=1)
        dateFrom = dateFromm.strftime('%Y-%m-%d')

        if Money.objects.filter(date_at=getTime(),
                                storage_id=storage_id).count() == 0:
            cash = request.POST["cash"]
            ak = Money(
                storage_id=storage_id,
                created_at=get_current_time().strftime("%Y-%m-%d %H:%M:%S"),
                date_at=getTime(),
                sum_cash_morning=cash,
            )
            ak.save()
            row = Money.objects.get(date_at=dateFrom, storage_id=storage_id)

            if row.sum_cash_end_day is None:
                sum_cash_end_day = 0
            else:
                sum_cash_end_day = row.sum_cash_end_day
            data = 'Заведение: ' + cafe + '%0A%0AКасса утро ' + get_current_time().strftime(
                '%Y-%m-%d %H:%M:%S') + ': ' + \
                   str(cash) + '%0AКасса вечер ' + dateFrom + ': ' + str(sum_cash_end_day) + \
                   '%0A%0AРазница: ' + str(int(cash) - int(sum_cash_end_day))
            send_webhk('chat_id', data, 1)
        else:
            cash = ''

        if Money.objects.filter(date_at=dateFrom, storage_id=storage_id).count() > 0:
            row = Money.objects.get(date_at=dateFrom, storage_id=storage_id)
            row2 = Money.objects.get(date_at=getTime(),
                                     storage_id=storage_id)

            if row2.sum_cash_morning is None:
                sum_cash_morning = 0
            else:
                sum_cash_morning = row2.sum_cash_morning

            if row.sum_cash_end_day is None:
                sum_cash_end_day = 0
            else:
                sum_cash_end_day = row.sum_cash_end_day

        if Timetable.objects.filter(date_at=getTime(),
                                    storage_id=storage_id, position='Тех. служащий').count() == 0:
            teh = request.POST["teh"]
        else:
            teh = 0
        teh_call = request.POST["teh_call"]

        if Money.objects.filter(date_at=getTime(),
                                storage_id=storage_id).count() > 0:
            if int(barmen) > 0:
                obj = Employee.objects.get(id=barmen)
                if Timetable.objects.filter(
                        date_at=getTime(),
                        storage_id=storage_id, employee_id=obj.id).count() == 0:
                    a = Timetable(
                        employee_id=obj.id,
                        storage_id=storage_id,
                        created_at=get_current_time().strftime("%Y-%m-%d %H:%M:%S"),
                        date_at=getTime(),
                        position='Бармен основной',
                        position_base_id=0,
                        oklad=obj.oklad
                    )
                    a.save()
            if int(barmen_call) > 0:
                obj = Employee.objects.get(id=barmen_call)
                if Timetable.objects.filter(
                        date_at=getTime(),
                        storage_id=storage_id, employee_id=obj.id).count() == 0:
                    oklad_barmen = obj.oklad
                    s = 'Бармен вызывной '
                    if int(call) == 2:
                        oklad_barmen = int(obj.oklad) - 400
                        s += '(усиление)'
                    elif int(call) == 1:
                        s += '(основной)'
                    a = Timetable(
                        employee_id=obj.id,
                        storage_id=storage_id,
                        created_at=get_current_time().strftime("%Y-%m-%d %H:%M:%S"),
                        date_at=getTime(),
                        position=s,
                        position_base_id=0,
                        oklad=oklad_barmen
                    )
                    a.save()
            if int(barmen_plus) > 0:
                obj = Employee.objects.get(id=barmen_plus)
                if Timetable.objects.filter(
                        date_at=getTime(),
                        storage_id=storage_id, employee_id=obj.id).count() == 0:
                    a = Timetable(
                        employee_id=obj.id,
                        storage_id=storage_id,
                        created_at=get_current_time().strftime("%Y-%m-%d %H:%M:%S"),
                        date_at=getTime(),
                        position='Бармен усиление',
                        position_base_id=0,
                        oklad=int(obj.oklad) - 400
                    )
                    a.save()
            if int(barmen_stazh) > 0:
                obj = Employee.objects.get(id=barmen_stazh)
                if Timetable.objects.filter(
                        date_at=getTime(),
                        storage_id=storage_id, employee_id=obj.id).count() == 0:
                    a = Timetable(
                        employee_id=obj.id,
                        storage_id=storage_id,
                        created_at=get_current_time().strftime("%Y-%m-%d %H:%M:%S"),
                        date_at=getTime(),
                        position='Бармен стажер',
                        position_base_id=0,
                        oklad='500'
                    )
                    a.save()
            if int(povar) > 0:
                obj = Employee.objects.get(id=povar)
                if Timetable.objects.filter(
                        date_at=getTime(),
                        storage_id=storage_id, employee_id=obj.id).count() == 0:
                    a = Timetable(
                        employee_id=obj.id,
                        storage_id=storage_id,
                        created_at=get_current_time().strftime("%Y-%m-%d %H:%M:%S"),
                        date_at=getTime(),
                        position='Повар основной',
                        position_base_id=0,
                        oklad=obj.oklad
                    )
                    a.save()
            if int(povar_plus) > 0:
                obj = Employee.objects.get(id=povar_plus)
                oklad = obj.oklad - 1300 if obj.type == 'Су-Шеф' else obj.oklad - 1100
                if obj.type == 'Бренд-Шеф':
                    oklad = 0
                if Timetable.objects.filter(
                        date_at=getTime(),
                        storage_id=storage_id, employee_id=obj.id).count() == 0:
                    a = Timetable(
                        employee_id=obj.id,
                        storage_id=storage_id,
                        created_at=get_current_time().strftime("%Y-%m-%d %H:%M:%S"),
                        date_at=getTime(),
                        position='Повар усиление',
                        position_base_id=0,
                        oklad=oklad
                    )
                    a.save()

templates/lk/employee_with_salary.html
{% extends 'base.html' %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <form action="{% url 'LK:employee_with_salary' %}">
                <div class="form-group">
                    <label for="month">Месяц {{ month }}</label>
                    <select id="month" name="month" class="form-select">
                        <option value="" selected>Выберите..</option>
                        <option value="01">Январь</option>
                        <option value="02">Февраль</option>
                        <option value="03">Март</option>
                        <option value="04">Апрель</option>
                        <option value="05">Май</option>
                        <option value="06">Июнь</option>
                        <option value="07">Июль</option>
                        <option value="08">Август</option>
                        <option value="09">Сентябрь</option>
                        <option value="10">Октябрь</option>
                        <option value="11">Ноябрь</option>
                        <option value="12">Декабрь</option>
                    </select>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn-sm btn-success"><i data-feather="filter"></i> Применить</button>
                </div>
            </form>
            <div class="table-responsive">
                <table id="table_id" class="table table-sm table-hover">
                    <thead>
                        <tr class="column-filter dt-column-filter">
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                            <th><input type="text" class="form-control form-control-sm" placeholder=""></th>
                        </tr>
                        <tr>
                            <th>Сотрудник</th>
                            <th>Начислено</th>
                            <th>Аванс</th>
                            <th>К выдаче</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for employee in employees %}
                            <tr>
                                <td>{{ employee.fio }}</td>
                                <td>
                                    {% for key, value in total.items %}
                                        {% if key == employee.id %}
                                            {{ value }}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for key, value in prepaid.items %}
                                        {% if key == employee.id %}
                                            {{ value }}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                                <td>
                                    {% for key, value in received.items %}
                                        {% if key == employee.id %}
                                            {{ value }}
                                        {% endif %}
                                    {% endfor %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <th></th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
    $(() => {
        // Run datatable
        var table = $('#table_id').DataTable({
            language: {
                "url": "//cdn.datatables.net/plug-ins/1.11.1/i18n/ru.json"
            },
            lengthMenu: [10, 25, 50, 100, 200, 500],
            pageLength: 25,
            responsive: true,

            drawCallback: function () {
                $('.dataTables_paginate > .pagination').addClass('pagination-sm') // make pagination small
            },
            footerCallback: function (row, data, start, end, display) {
                var api = this.api();
                // Remove the formatting to get integer data for summation
                var intVal = function (i) {
                    return typeof i === 'string' ?
                        i.replace(/[\$,]/g, '') * 1 :
                        typeof i === 'number' ?
                            i : 0;
                };
                pageTotal4 = api.column(1, { page: 'current' }).data().reduce(function (a, b) {
                    return intVal(a) + intVal(b);
                }, 0);
                // Update footer
                $(api.column(1).footer()).html(
                    '' + pageTotal4  //+ ' (' + total4 + ' total)'
                );
                pageTotal4 = api.column(2, { page: 'current' }).data().reduce(function (a, b) {
                    return intVal(a) + intVal(b);
                }, 0);
                // Update footer
                $(api.column(2).footer()).html(
                    '' + pageTotal4  //+ ' (' + total4 + ' total)'
                );
                pageTotal4 = api.column(3, { page: 'current' }).data().reduce(function (a, b) {
                    return intVal(a) + intVal(b);
                }, 0);
                // Update footer
                $(api.column(3).footer()).html(
                    '' + pageTotal4  //+ ' (' + total4 + ' total)'
                );
            }

        })
        // Apply column filter
        $('#table_id .dt-column-filter th').each(function (i) {
            $('input', this).on('keyup change', function () {
                if (table.column(i).search() !== this.value) {
                    table
                        .column(i)
                        .search(this.value)
                        .draw()
                }
            })
        })
        // Toggle Column filter function
        var responsiveFilter = function (table, index, val) {
            var th = $(table).find('.dt-column-filter th').eq(index)
            val === true ? th.removeClass('d-none') : th.addClass('d-none')
        }
        // Run Toggle Column filter at first
        $.each(table.columns().responsiveHidden(), function (index, val) {
            responsiveFilter('#table_id', index, val)
        })
        // Run Toggle Column filter on responsive-resize event
        table.on('responsive-resize', function (e, datatable, columns) {
            $.each(columns, function (index, val) {
                responsiveFilter('#table_id', index, val)
            })
        })
    })
</script>
{% endblock %}

templates/lk/header.html
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="/">Хмельной повар</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
        data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="/logout">Выйти</a>
        </div>
    </div>
</header>

templates/lk/lk_expenses_new.html
{% extends 'lk/form_base.html' %}

{% block content %}
    <div class="card-header">
        Создание расхода
    </div>
    <div class="card-body">
        <form action="{% url 'LK:lk_expenses_new' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="date">Дата</label>
                <input type="text" name="date" id="date" placeholder="Выберите дату" class="form-control">
            </div>
            <div class="form-group">
                <label for="sum">Сумма</label>
                <input type="tel" name="sum" id="sum" placeholder="Введите сумму" class="form-control">
            </div>
            <div class="form-group">
                <label for="storage">Заведение</label>
                <select name="storage" id="storage" class="form-select">
                    {% for storage in storages %}
                        <option value="{{storage.id}}">{{storage.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="pay_type">Тип оплаты</label>
                <select name="pay_type" id="pay_type" class="form-select">
                    <option value="Из кассы">Из кассы</option>
                    <option value="Картой">Картой</option>
                </select>
            </div>
            <div class="form-group">
                <label for="expense">Расход</label>
                <select name="expense" id="expense" class="form-select">
                    {% for expense in expenses %}
                        <option value="{{ expense.text }}">{{ expense.text }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="comment">Комментарий</label>
                <input type="text" id="comment" name="comment" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Сохранить</button>
        </form>
    </div>
{% endblock %}

{% block scripts %}
<script>
    $(function(){
        $("#date").datepicker();
    });
</script>
{% endblock %}

templates/lk/lk_pays_edit.html
{% extends 'lk/form_base.html' %}

{% block content %}
    <div class="card-header">
        Редактирование записи
    </div>
    <div class="card-body">
        <form action="{% url 'LK:lk_pays_edit' id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="date">Дата</label>
                <input type="text" name="date" id="date" value="{{ row.date_at }}" class="form-control">
            </div>
            <div class="form-group">
                <label for="type">Тип</label>
                <select class="form-select" name="type" id="type">
                    <option value="1" {% if row.type == 1 %}selected{% endif %}>Внесение</option>
                    <option value="2" {% if row.type == 2 %}selected{% endif %}>Изъятие</option>
                </select>
            </div>
            <div class="form-group">
                <label for="comment">Комментарий</label>
                <select id="comment" name="comment" class="form-select">
                    {% for record in records %}
                        {% if record.text == row.comment %}
                            <option value="{{ row.comment }}" selected>{{ row.comment }}</option>
                        {% else %}
                            <option value="{{ record.text }}">{{ record.text }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="sum">Сумма</label>
                <input class="form-control" id="sum" name="sum" value="{{ row.sum }}">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Сохранить</button>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $(function() {
            $('#date_at').datepicker()
        })
    </script>
{% endblock %}

templates/lk/lk_timetable_new.html
{% extends 'lk/form_base.html' %}

{% block content %}
<div class="card mb-4">
    <div class="card-header">
        Создание расписания
    </div>
    <div class="card-body">
        <form action="{% url 'LK:lk_timetable_new' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="date">Дата</label>
                <input type="text" name="date" id="date" placeholder="Выберите дату" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="employee">Сотрудник</label>
                <select name="employee" id="employee" class="form-select" required>
                    {% for employee in employees %}
                        <option value="{{ employee.id }}">{{ employee.fio }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="storage_id">Заведение</label>
                <select name="storage_id" id="storage_id" class="form-select" required>
                    {% for storage in storages %}
                        <option value="{{ storage.id }}">{{ storage.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="oklad">Оклад</label>
                <input type="tel" name="oklad" id="oklad" class="form-select" required>
            </div>
            <div class="form-group">
                <label for="position">Позиция</label>
                <select name="position" id="position" required>
                    <option value="Бармен основной">Бармен основной</option>
                    <option value="Бармен усиление">Бармен усиление</option>
                    <option value="Бармен вызывной">Бармен вызывной</option>
                    <option value="Бармен стажер">Бармен стажер</option>
                    <option value="Повар основной">Повар основной</option>
                    <option value="Повар усиление">Повар усиление</option>
                    <option value="Повар вызывной">Повар вызывной</option>
                    <option value="Повар стажер">Повар стажер</option>
                    <option value="Тех. служащий">Тех. служащий</option>
                    <option value="Тех. служащий вызывной">Тех. служащий</option>
                </select>
            </div>
            <button type="submit" class="btn btn-success">Создать</button>
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(function(){
        $("#date").datepicker();
    });
</script>
{% endblock %}